### ISSUE TITLE
ntfsusermap generates SIDs not present on Windows

### ISSUE THREAD

**Issue by Thibaulltt** [tuxera/ntfs-3g#125]
I have two drives on my system which I'd like to share between Windows and Linux. The main use cases are for sharing a Steam library and mass storage. I have used `ntfsusermap` to generate a user mapping file, and have edited my `/etc/fstab` to mount the drives automatically on startup.

However, when I boot back into Windows, the files on *only one of my drives* are now owned by a SID which does not exist on my Windows. See the following:

```
# Files are owned by (as seen in win explorer):
S-<long number>-1000
# The following command in a admin cmd:
# > wmic useraccount get name,sid
# returns:
Administrator      S-<long number>-500
User 1             S-<long number>-1002
DefaultAccount     S-<long number>-503
Guest              S-<long number>-501
User 2             S-<long number>-1003
User 3             S-<long number>-1001
WDAGUtilityAccount S-<long number>-504
```

This leaves me with three questions:

1. I'm quite uneducated on how Windows works, but I assume SIDs are constant ? Why are all my files owned by this SID which does not exist on my Windows system ?
2. Furthermore, can I replace that SID from the `UserMapping` to my own file without any consequences ?
3. How can I restore my original permissions and ownership once booted back into Windows ? The `takeown` utility does not seem to be enough for Steam: it still complains about "Missing file privileges" even though I own the folder as per the last `takeown` invocation.

For the record, I have generated the `UserMapping` file from Linux (Fedora 40) when the Windows drives were mounted manually with default options.

**Comment by jpandre** [comment]
> However, when I boot back into Windows, the files on only one of my drives are now owned by a SID which does not exist on my Windows.

If your drives do not behave the same way on Linux, they probably do not have identical UserMapping descriptions. If they do not behave the same way on Windows, their roots probably define different inheritance policies (was one drive used on another computer ?).

> Files are owned by (as seen in win explorer):
> S-<long number>-1000

This is the first user which was configured after Windows was installed. Usually this is the only user.

> Administrator      S-<long number>-500
> User 1             S-<long number>-1002
> DefaultAccount     S-<long number>-503
> Guest              S-<long number>-501
> User 2             S-<long number>-1003
> User 3             S-<long number>-1001
> WDAGUtilityAccount S-<long number>-504

The SIDs ending in 50x are for generic users, they should not appear as owners of user files. Those ending in 100x are for other configured users.

> I assume SIDs are constant ?

They identify the owner of files. They only change upon request.

> Why are all my files owned by this SID which does not exist on my Windows system ?

If "this SID" means the SID ending in 1000, this is expected for all files created by the first user. I do not know why this SID does not show in your list (I do not know what your list is expected to show).

> Furthermore, can I replace that SID from the UserMapping to my own file without any consequences ?

On Linux you just have to do a chown. On Windows this is not straighforward. If the SID ends in 1000, you probably do not want to change anything.

> How can I restore my original permissions and ownership once booted back into Windows ? The takeown utility does not seem to be enough for Steam: it still complains about "Missing file privileges" even though I own the folder as per the last takeown invocation.

Your issue is probably not related to ownership of files. Regarding permissions you have to consider that Windows and Linux do not act the same way when creating new files : Windows applies inheritance, and Linux does not. However "Missing file privileges" does not sound like a permission issue either.

You might want to use Windows to copy your suspect files into a directory created by the target Windows user. This should set this user as the owner, and set the inherited permissions.

**Comment by Thibaulltt** [comment]
Thanks for the quick answer :)

You raise an interesting point. My "problematic" drive (`A:`) was used in another computer before. Might the `S-*-1000` SID be the SID of my personal user account on the old computer? This might explain why it does not show using `wmic` on Windows.

In my particular case, I have 3 users on both the Windows and Linux side. They should all have r/w permissions on both of those drives as they are shared for games and data. In order to allow all users to read/write on Linux I created a nologin user (`uid=666`) and a system group (`gid=666`). I then mapped some Windows paths `ntfsusermap` gave me that I did not recognize (/Users/Public, some internal WindowsApps paths) to it. Would this cause any problems on the windows side ?

As for the "Missing file privileges", I have compared some of the permissions on my `A:` drive to some on my `C:` drive (which I never mounted on Linux) and the permissions for the system administrators and regular users match. Which is why I thought of ownership, as it seemed to be the only differentiating factor between all of them... I'm going to try your method, thanks!

**Comment by Thibaulltt** [comment]
@jpandre Going back to your comment: the "move to a known good folder" trick you mentionned worked! I'm closing this issue now.

There's still the issue of having all 3 users on the Windows and Linux side being able to r/w to those disks, but this is more suited to a forum than this repo's Github issues.

Thanks!
