### ISSUE TITLE
Mac: FUSE-T and Apple Silicon support, docs

### ISSUE THREAD

**Issue by ilyagr** [tuxera/ntfs-3g#130]
I wish ntfs-3g supported [fuse-t](https://github.com/macos-fuse-t/fuse-t) or some other way to run on Mac OS without a kernel extension. Kernel extensions are hard to install on Apple Silicon.

I'm also not sure whether recent Mac OS on apple silicon provides enough access to the low-level disk device to mount it as NTFS. Docs about whether that works, and how to compile/use ntfs-3g on apple silicon would be welcome.

One way to install Ntfs-3g on a mac I found is via [Nix](https://search.nixos.org/packages?channel=unstable&type=packages&query=ntfs-3g), but it couldn't find/use FUSE-T.

```console
$ ntfs-3g
dyld[79644]: Library not loaded: /usr/local/lib/libfuse.2.dylib
  Referenced from: <9BC8FDCB-C6A7-301A-AEA3-A156788CFA19> /nix/store/mjy5qmy0gvvk96lj6rkhdk8ng2r1wy73-ntfs3g-2022.10.3/bin/ntfs-3g
  Reason: tried: '/usr/local/lib/libfuse.2.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/libfuse.2.dylib' (no such file), '/usr/local/lib/libfuse.2.dylib' (no such file), '/usr/lib/libfuse.2.dylib' (no such file, not in dyld cache)
fish: Job 1, 'ntfs-3g' terminated by signal SIGABRT (Abort)
```

**Comment by unsound** [comment]
I think this issue is really two issues, none of which is really related to ```ntfs-3g``` itself:
1. I'm sure that if FUSE-T has a ```libfuse``` compatible library then you could easily build ```ntfs-3g``` to use it. AFAIK this was not attempted, instead you used a prebuilt binary that links against macfuse's ```libfuse``` and that's not going to work. If you have any issues building ```ntfs-3g``` against FUSE-T's ```libfuse``` then you should file an issue with the FUSE-T project. I wouldn't get too excited about FUSE-T though, it's an NFS server which means that it can't provide anywhere near the same level of system integration that macfuse does, so realistically it's not much of an option for local filesystems if you really can't use kernel extensions due to company policies that you can't change (maybe it can be a good option for FUSE-based network filesystems though).
2. Kernel extensions are hard to install, which is something that you can only report to Apple. Apple have made it difficult for third party filesystem providers with this requirement without offering an alternative way forward (the mythical FSKit is still to be launched officially) and if this is an issue for you then I'd say make your voice heard.

So I'm closing this issue as there's seemingly nothing to do about it as far as ```ntfs-3g``` is concerned.

Edit: Regarding building ntfs-3g, it's a pretty standard autotools/pkg-config project. It builds just like any other similar project and the only tools required are tools that are provided by default in macOS (at least after installing the command line developer tools, ```xcode-select --install```).

**Comment by ilyagr** [comment]
Thanks, this sounds reasonable, it's perfectly reasonable to consider this a packaging issue.

One stumbling block for me was a lack of detailed build instructions: how would I point it to FUSE-T? I can find its `dylib` file, but I am only very vaguely familiar with pkg-config, so I'm not sure what option to pass to the configure script. If I figure out how to do it, I might try to add it to the wiki.

Currently, the configure script fails with:

```
checking for fuse >= 2.6.0... no
configure: error: FUSE >= 2.6.0 was not found. Either older FUSE is still present, or FUSE is not fully installed (e.g. fuse, libfuse, libfuse2, libfuse-dev, etc packages). Source code: http://fuse.sf.net
```

Your point that FUSE-T might not work very well is good to know. Hopefully, the mythical FSKit will appear and be better; it seems likely that Mac OS kexts are about to die.

**Comment by matthewhartstonge** [comment]
@ilyagr I ran `brew install macfuse` to fix the above configure script failure if that helps with docs/nix config.
