### ISSUE TITLE
Editing Windows while hibernated and remove_hiberfile

### ISSUE THREAD

**Issue by sudo-jade** [tuxera/ntfs-3g#34]
The remove_hiberfile option failed to work while I was trying to mount Windows as writeable. I would be willing to look into this myself and create a possible workaround that does **not** require disabling fast restart in order to edit a Windows partition and keeps the changes after Windows restarts. 

In order to edit my Windows partition I was forced to remove all checks of hibernation from the source code and compile myself. It would be great if there was a working command line option that could do this instead.

**Comment by jpandre** [comment]
> The remove_hiberfile option failed to work while I was trying to mount Windows as writeable.

Windows 10 has a different way for storing the hibernate data, and removing the hibernate file is not enough any more.

> I would be willing to look into this myself and create a possible workaround that does not require disabling fast restart in order to edit a Windows partition and keeps the changes after Windows restarts.

Your proposal for restoring the latest consistency state of the data will be appreciated. Currently there are three options, only the first one is safe :

1) reboot into Windows and leave it by doing "Restart" instead of "Shut down". This is the recommended way.

or

2) unmount the partition, apply "ntfsrecover --kill-fast-restart" and remount. This tries to keep the recent updates, but may fail.

or

3) unmount the partition, apply "ntfsfix -d" and remount. This will probably cause some recently written data to be lost.

> In order to edit my Windows partition I was forced to remove all checks of hibernation from the source code and compile myself. It would be great if there was a working command line option that could do this instead.

Applying "ntfsfix -d" will do just that, but you may lose some data.
