### ISSUE TITLE
./configure not working?

### ISSUE THREAD

**Issue by niiccoo2** [tuxera/ntfs-3g#51]
![Screenshot_2022-07-27_07-43-29](https://user-images.githubusercontent.com/101956935/181238719-a876dea9-3ba9-4db6-90f0-0968401faf26.png)

**Comment by iFreilicht** [comment]
You might want to run `./autogen.sh` instead, it checks for version compatibility and runs autoconf with the correct flags. The README is unclear here, I'll submit a PR for that.

**Comment by iFreilicht** [comment]
Alright, done: #55

**Comment by unsound** [comment]
This doesn't look like an actual issue. If you are not a developer then please download the source tarball, which has all the autogenerated files needed to get started without any additional steps. Otherwise you need to know your way around the autotools build system. Will also consider #55 but I'm closing this issue for now.
